default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: storage/cats.sqlite3

development:
  <<: *default

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
